<?php

return [
    'themes' => [
        'light' => [
            'name' => 'Light',
            'colors' => [
                'primary' => '#ffffff',
                'secondary' => '#f3f4f6',
                'accent' => '#3b82f6',
                'text' => '#1f2937',
                'text-light' => '#6b7280',
                'border' => '#e5e7eb',
                'success' => '#10b981',
                'warning' => '#f59e0b',
                'error' => '#ef4444',
                'info' => '#3b82f6',
            ],
        ],
        'dark' => [
            'name' => 'Dark',
            'colors' => [
                'primary' => '#1f2937',
                'secondary' => '#111827',
                'accent' => '#60a5fa',
                'text' => '#f9fafb',
                'text-light' => '#d1d5db',
                'border' => '#374151',
                'success' => '#34d399',
                'warning' => '#fbbf24',
                'error' => '#f87171',
                'info' => '#60a5fa',
            ],
        ],
        'blue' => [
            'name' => 'Blue',
            'colors' => [
                'primary' => '#1e40af',
                'secondary' => '#1e3a8a',
                'accent' => '#60a5fa',
                'text' => '#ffffff',
                'text-light' => '#bfdbfe',
                'border' => '#3b82f6',
                'success' => '#34d399',
                'warning' => '#fbbf24',
                'error' => '#f87171',
                'info' => '#60a5fa',
            ],
        ],
        'green' => [
            'name' => 'Green',
            'colors' => [
                'primary' => '#065f46',
                'secondary' => '#064e3b',
                'accent' => '#34d399',
                'text' => '#ffffff',
                'text-light' => '#a7f3d0',
                'border' => '#10b981',
                'success' => '#34d399',
                'warning' => '#fbbf24',
                'error' => '#f87171',
                'info' => '#60a5fa',
            ],
        ],
        'purple' => [
            'name' => 'Purple',
            'colors' => [
                'primary' => '#5b21b6',
                'secondary' => '#4c1d95',
                'accent' => '#a78bfa',
                'text' => '#ffffff',
                'text-light' => '#c4b5fd',
                'border' => '#8b5cf6',
                'success' => '#34d399',
                'warning' => '#fbbf24',
                'error' => '#f87171',
                'info' => '#60a5fa',
            ],
        ],
    ],
]; 